# Generated by Django 4.1.10 on 2023-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.TextField(blank=True, null=True, verbose_name='Brands'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.TextField(blank=True, null=True, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Image Url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Packaing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantity'),
        ),
    ]
