version: '3.8'

services:
  # ---------------------------------------------------------------------------
  # Mongo DB
  # ---------------------------------------------------------------------------
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=challange
      - MONGO_INITDB_ROOT_PASSWORD=challange
      - MONGO_INITDB_DATABASE=challange


  # ---------------------------------------------------------------------------
  # Redis
  # ---------------------------------------------------------------------------
  redis:
    container_name: challange-redis
    image: redis:latest
    restart: on-failure
    ports:
      - 6379:6379

  # ---------------------------------------------------------------------------
  # RabbitMQ
  # ---------------------------------------------------------------------------
  rabbitmq:
    container_name: challange-rabbitmq
    image: rabbitmq:latest
    restart: on-failure
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  database-data:
    driver: local
